[project]
name = "stardist8"
authors = ["bnorthan <bnorthan@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[dependencies]
python = "3.10.*"
napari = "<0.7"
pyqt = "*"
stardist = "<0.9"
setuptools = "<71"

[target.linux-64.dependencies]
cudnn = "*"
cudatoolkit = "*"

[target.win-64.dependencies]
cudatoolkit = "11.8.*"
cudnn = "8.1.0.*"

[pypi-dependencies]
tensorflow = ">=2.0"
tnia-python = { git = "https://github.com/True-North-Intelligent-Algorithms/tnia-python.git" }
# tnia-python = { path = "C:/Users/bnort/work/ImageJ2022/tnia/tnia-python", editable=true }

appose = "*"

# napari-ai-lab = { git = "https://github.com/True-North-Intelligent-Algorithms/napari-ai-lab" }
napari-ai-lab = { path = "C:/Users/bnort/work/ImageJ2022/tnia/napari-ai-lab", editable=true}

# tensorflow needs to be below 2.11 for GPU support on windows
[target.win-64.pypi-dependencies]
tensorflow = "<2.11"
