# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.0
_src_path: https://github.com/napari/napari-plugin-template
display_name: Napari AI Lab
email: bnorthan@gmail.com
full_name: Brian Northan
github_repository_url: provide later
github_username_or_organization: bnorthan
include_reader_plugin: false
include_sample_data_plugin: false
include_widget_plugin: true
include_writer_plugin: true
install_dependabot: true
install_precommit: true
license: BSD-3
module_name: napari_ai_lab
plugin_name: napari-ai-lab
short_description: A collection of plugins and utilities for ND segmentation with
    Cellpose, StarDist, SAM and more
